```{r}
library(ggplot2)
library(tidyverse)
library(lubridate)
library(dbplyr)
install.packages("dygraphs")
install.packages("xts")
library(dygraphs)
library(xts)
library(forcats)

```

```{r}
#Part 1: Summary statistics of trips intraday, across weekdays and weekends 

taxitrips <-read.csv("Trips by days.csv")
head(taxitrips)
str(taxitrips)
taxitrips$trips <- as.numeric(taxitrips$trips)
taxitrips$trip_date <-dmy(taxitrips$trip_date)
taxitrips$Month <-as.factor(taxitrips$Month)
str(taxitrips)

```
```{r}
#linechart - across the months 

p <-taxitrips %>%  group_by(trip_date) %>%  summarise(trips=sum(trips)) %>% ggplot(aes(x=trip_date, y=trips)) +
  geom_line() + 
  geom_smooth(color ="steelblue", se = FALSE) +
  xlab("") + ylab("# of Trips")

p+scale_x_date(date_breaks = "1 month",date_labels = "%b") 

```
```{r}
#trips- across the months 

taxitrips %>%  group_by(trip_date) %>%  summarise(trips=sum(trips)) %>% ggplot(aes(x=trip_date, y=trips)) +
  geom_area (fill = "#69b3a2" , alpha = 0.7) +
  geom_line (colour = "#69b3a2", size = 1) +
  geom_smooth(se = FALSE) +
  geom_point(size = 0.5, color="#69b3a2")+
  ggtitle ("Taxi trips across 2019")+
  xlab("Months") + ylab("# of Trips")+
  scale_x_date(date_breaks = "1 month",date_labels = "%b") 
```
```{r}
#trips across the seasons 

p1 <-taxitrips %>% group_by(trip_date, Season) %>%  summarise(trips=sum(trips)) %>% 
  mutate (Season = fct_relevel(as.factor(Season),
                               "Spring","Summer",
                               "Autumn","Winter")) %>%
  ggplot(aes(x=Season, y=trips, fill=Season)) +
  geom_boxplot(alpha = 0.3) + 
  theme (legend.position = "none") +
  scale_fill_brewer(palette = "Reds") +
  xlab("Seasons") + ylab("# of Trips") +
  ggtitle ("Taxi trips across the seasons of 2019")

p1




```

```{r}
str(taxitrips)
```

```{r}
#trips across the week 

stat_box_data <- function(x, upper_limit = 90000 ) {
  return( 
    data.frame(
      y = 0.95 * upper_limit,
      label = paste('count =', 
                    format(length(x), big.mark = ",", decimal.mark = ".", scientific = FALSE), 
                    '\n',
                    'mean =', 
                    format(round(mean(x), 1), big.mark = ",", decimal.mark = ".", scientific = FALSE))
    )
  )
}

p2 <- taxitrips %>% group_by(trip_date, Day) %>%  summarise(trips=sum(trips)) %>% 
  mutate (Day = fct_relevel(as.factor(Day),
                           "MONDAY","TUESDAY",
                           "WEDNESDAY","THURSDAY",
                           "FRIDAY", "SATURDAY",
                           "SUNDAY")) %>%
  ggplot(aes(x=Day, y=trips, fill=Day)) +
    geom_boxplot(alpha = 0.8) + 
    geom_jitter(color="black",size=0.2,alpha=0.4) +
    theme (legend.position = "none") +
    scale_fill_brewer(palette = "Blues") +
    xlab("Week") + ylab("# of Trips") +
    ggtitle ("Taxi trips across the week")+
     stat_summary(
    fun.data = stat_box_data, 
    geom = "text", 
    hjust = 0.5,
    vjust = 0.9,
    size = 3
  )
p2

```
```{r}
#trips across the time periods 

library(viridis)

p3 <- taxitrips %>%
  mutate (Day = fct_relevel(as.factor(taxitrips$time_indicator),
                           "AM Period","Lunch Period",
                           "PM Period", "Night")) %>%
  ggplot(aes(x=Day, y=trips, fill=time_indicator)) +
    geom_violin() +
    scale_fill_viridis(discrete=TRUE, alpha = 0.6, option = "A") +
    theme (legend.position = "none") +
    scale_fill_brewer(palette = "Greens") +
    xlab("Intraday") + ylab("# of Trips") +
    ggtitle ("Taxi trips across intraday")

p3

```


